// @ts-check
/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  sanctuarySidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  caseStudiesSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

module.exports = sidebars;
