/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated', 
      dirName: '.'
    },
    {
      type: 'category',
      label: 'Guinea Pigs',
      items: [
        'guinea-pigs/cl',
        'guinea-pigs/guineapigcare',
        'guinea-pigs/guineapigpoop',
        'guinea-pigs/lethalwhite',
        'guinea-pigs/lymphoma',
        'guinea-pigs/ovariancysts',
        'guinea-pigs/satinsyndrome',
      ],
    },
    {
      type: 'category',
      label: 'So You Want to Run a Rescue',
      items: [
        'rescue/budget',
        'rescue/transparency',
        'rescue/vets',
      ],
    },

  ],

  // But you can create a sidebar manually
  
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
};

module.exports = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  sanctuarySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // assumes sidebar is autogenerated from /sanctuary
    },
  ],
};

export default sidebars;
